from copy import deepcopy


BOT_PRESETS = [
    {
        "id": "preset_ema_conservador_btc",
        "name": "EMA Conservador BTC",
        "description": "Cruce EMA clásico para BTC con baja frecuencia de señales y riesgo moderado.",
        "market_type": "tendencia_suave",
        "risk_level": "bajo",
        "strategy": "ema_cross",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "ema_cross",
            "fast_ema": 12,
            "slow_ema": 26,
            "capital_allocation": 500,
            "executor": "paper",
            "risk_config": {"max_drawdown": 0.04},
        },
    },
    {
        "id": "preset_ema_conservador_eth",
        "name": "EMA Conservador ETH",
        "description": "Versión conservadora para ETH en marcos tendenciales de volatilidad media.",
        "market_type": "tendencia_suave",
        "risk_level": "bajo",
        "strategy": "ema_cross",
        "config": {
            "symbol": "ETH/USDT",
            "strategy": "ema_cross",
            "fast_ema": 10,
            "slow_ema": 30,
            "capital_allocation": 500,
            "executor": "paper",
            "risk_config": {"max_drawdown": 0.04},
        },
    },
    {
        "id": "preset_technical_pro_balanced",
        "name": "Technical Pro Balanceado",
        "description": "Filtro técnico multi-indicador para mercado mixto con sesgo conservador.",
        "market_type": "mixto",
        "risk_level": "medio-bajo",
        "strategy": "technical_pro",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "technical_pro",
            "capital_allocation": 500,
            "executor": "paper",
            "risk_config": {"max_drawdown": 0.05},
        },
    },
    {
        "id": "preset_algo_expert_defensivo",
        "name": "Algo Expert Defensivo",
        "description": "Estrategia híbrida orientada a evitar sobreoperación en condiciones inciertas.",
        "market_type": "mixto",
        "risk_level": "medio-bajo",
        "strategy": "algo_expert",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "algo_expert",
            "capital_allocation": 500,
            "executor": "paper",
            "risk_config": {"max_drawdown": 0.05},
        },
    },
    {
        "id": "preset_grid_btc_wide",
        "name": "Grid BTC Rango Amplio",
        "description": "Grid con pocas rejillas y rango amplio para mercados laterales menos ruidosos.",
        "market_type": "lateral_amplio",
        "risk_level": "bajo",
        "strategy": "grid_trading",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "grid_trading",
            "upper_limit": 72000,
            "lower_limit": 58000,
            "num_grids": 8,
            "capital_allocation": 500,
            "executor": "paper",
            "risk_config": {"max_drawdown": 0.04},
        },
    },
    {
        "id": "preset_grid_btc_tight",
        "name": "Grid BTC Rango Controlado",
        "description": "Grid más activo con rango controlado para consolidaciones estables.",
        "market_type": "lateral_controlado",
        "risk_level": "medio-bajo",
        "strategy": "grid_trading",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "grid_trading",
            "upper_limit": 68000,
            "lower_limit": 62000,
            "num_grids": 12,
            "capital_allocation": 500,
            "executor": "paper",
            "risk_config": {"max_drawdown": 0.05},
        },
    },
    {
        "id": "preset_grid_eth_stable",
        "name": "Grid ETH Estable",
        "description": "Grid moderado para ETH en tramos laterales con volatilidad media.",
        "market_type": "lateral_amplio",
        "risk_level": "medio-bajo",
        "strategy": "grid_trading",
        "config": {
            "symbol": "ETH/USDT",
            "strategy": "grid_trading",
            "upper_limit": 4200,
            "lower_limit": 2800,
            "num_grids": 10,
            "capital_allocation": 500,
            "executor": "paper",
            "risk_config": {"max_drawdown": 0.05},
        },
    },
    {
        "id": "preset_dynamic_reinvest_safe",
        "name": "Dynamic Reinvest Seguro",
        "description": "Toma beneficio frecuente y reinversión parcial para crecimiento controlado.",
        "market_type": "tendencia_media",
        "risk_level": "medio",
        "strategy": "dynamic_reinvest",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "dynamic_reinvest",
            "take_profit_pct": 0.02,
            "capital_allocation": 500,
            "executor": "paper",
            "risk_config": {"max_drawdown": 0.05},
        },
    },
    {
        "id": "preset_technical_pro_range_filter",
        "name": "Technical Pro con Filtro de Rango",
        "description": "Technical Pro con límites de rango para reducir entradas en extremos.",
        "market_type": "mixto",
        "risk_level": "medio-bajo",
        "strategy": "technical_pro",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "technical_pro",
            "upper_limit": 70000,
            "lower_limit": 60000,
            "num_grids": 10,
            "capital_allocation": 500,
            "executor": "paper",
            "risk_config": {"max_drawdown": 0.05},
        },
    },
    {
        "id": "preset_ema_swing_defensivo",
        "name": "EMA Swing Defensivo",
        "description": "EMA de swing con periodos largos para filtrar ruido en mercados volátiles.",
        "market_type": "tendencia_volatil",
        "risk_level": "medio-bajo",
        "strategy": "ema_cross",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "ema_cross",
            "fast_ema": 20,
            "slow_ema": 50,
            "capital_allocation": 500,
            "executor": "paper",
            "risk_config": {"max_drawdown": 0.05},
        },
    },
    {
        "id": "preset_auto_agresivo",
        "name": "Auto Gestión Agresiva",
        "description": "Bot autogestionado orientado a crecimiento acelerado con reinversión alta y riesgo elevado controlado.",
        "market_type": "tendencia_volatil",
        "risk_level": "alto",
        "strategy": "adaptive_learning",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "adaptive_learning",
            "adaptive_short_window": 8,
            "adaptive_long_window": 30,
            "adaptive_base_amount": 0.018,
            "capital_allocation": 600,
            "executor": "paper",
            "self_managed": True,
            "reinvest_ratio": 0.55,
            "min_allocation": 120,
            "max_allocation": 5000,
            "leverage": 2,
            "risk_config": {"max_drawdown": 0.06},
        },
    },
    {
        "id": "preset_auto_balanceado",
        "name": "Auto Gestión Balanceada",
        "description": "Bot autogestionado equilibrado para crecer capital de forma sostenida con ajustes dinámicos de riesgo.",
        "market_type": "mixto",
        "risk_level": "medio",
        "strategy": "adaptive_learning",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "adaptive_learning",
            "adaptive_short_window": 10,
            "adaptive_long_window": 36,
            "adaptive_base_amount": 0.012,
            "capital_allocation": 500,
            "executor": "paper",
            "self_managed": True,
            "reinvest_ratio": 0.4,
            "min_allocation": 100,
            "max_allocation": 3500,
            "leverage": 1.5,
            "risk_config": {"max_drawdown": 0.045},
        },
    },
    {
        "id": "preset_auto_defensivo",
        "name": "Auto Gestión Defensiva",
        "description": "Bot autogestionado conservador con priorización de supervivencia de capital y aprendizaje progresivo.",
        "market_type": "tendencia_suave",
        "risk_level": "bajo",
        "strategy": "adaptive_learning",
        "config": {
            "symbol": "BTC/USDT",
            "strategy": "adaptive_learning",
            "adaptive_short_window": 14,
            "adaptive_long_window": 55,
            "adaptive_base_amount": 0.008,
            "capital_allocation": 400,
            "executor": "paper",
            "self_managed": True,
            "reinvest_ratio": 0.25,
            "min_allocation": 80,
            "max_allocation": 2500,
            "leverage": 1,
            "risk_config": {"max_drawdown": 0.03},
        },
    },
]


def list_bot_presets():
    return deepcopy(BOT_PRESETS)


def get_bot_preset(preset_id: str):
    for preset in BOT_PRESETS:
        if preset["id"] == preset_id:
            return deepcopy(preset)
    return None
